### ISSUE TITLE
Quirky focus

### ISSUE THREAD

**Issue by lrporder** [sriram-24/PinInputMendix#1]
Description:
The widget takes input the right way, but shows (and keeps showing) focus the wrong way if you focused the wrong box manually.

To reproduce:
Click for example the 3rd box to start typing. The 3rd box will be focused (this should be the 1st). Your input will go to the 1st box, which is ok, but focus will now shift to the 4th box, and so on until the last box stays focused while you finish your input.
The same if you click a random box and use backspace to correct things. This should start at the end.

Expected:
If you click the input boxes, it should take the boxes as one input field and focus either the first box if the input is still empty or the last filled in box.
Maybe it would also help to (optionally) steal focus right away so the user can start typing without first clicking the input.

**Comment by sriram-24** [comment]
Quirky focus issue has been fixed from v1.0.2. 

User can enter text from any input boxes and it will focus to the last filled area after the key is released. Like the below. Tryout the updated widget [here](https://pininputtest-sandbox.mxapps.io/)

https://github.com/user-attachments/assets/b70ae552-db2d-47c2-81bf-da5a53011b9a

Focus stealing at the initial load of the page is somehow not working in Mendix page. The reason for it is yet to be found. 

Closing this issue as it is resolved. Feel free to re-open if it is not working.
